spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/pps
    username: pps
    password: pps
    thymeleaf: cache=false

  jpa:
    hibernate:
      ddl-auto:  "update"
